### ISSUE TITLE
Win 11 23H2 (25967.1010) LG C2 Profile is greyed out

### ISSUE THREAD

**Issue by SergeDubovsky** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#23]
I wonder if I am missing something. The profile is added as HDR and set to default.
![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/1774209/399c2c46-2b61-4670-a8da-c72b2c1fa612)
But the color profile is not picking up anything:
![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/1774209/6c26612f-49ae-43ff-a881-71eb695a0e32)

Have I missed something somewhere?
Thank you!

**Comment by dylanraga** [comment]
This happens when you have "Automatically manage color for apps" enabled under "Advanced display". HDR already uses this feature internally, and it only matters for SDR. I believe it's a bug that it doesn't display HDR profiles in the dropdown, but it should properly apply.

**Comment by Animesh-Does-Code** [comment]
>But when SDR is played on LG OLED, something tries to "upscale" it to HDR and colors are completely destroyed. Have you happen to see anything similar?

According to [this](https://www.reddit.com/r/nvidia/comments/179y9gc/comment/k59ax7g/?utm_source=reddit&utm_medium=web2x&context=3) comment on the Nvidia subreddit, that is a Chromium bug that will be fixed in the next release (v119). Until then, you can add `--disable_vp_auto_hdr` to your Chrome/Edge shortcut to work around the issue. Attached a screenshot on how the shortcut should look in case it's needed. 

![image](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/assets/143435411/c703984b-c883-40ae-8fbe-51442542d717)

This workaround applies to any Chromium based browser, not just Chrome and Edge.

Alternatively you could install the beta version of your browser, which might have already implemented a fix for this bug if it's on version 119 or above.
