### ISSUE TITLE
Question about 800 nits and windows SDR\HDR slider..

### ISSUE THREAD

**Issue by bwellington1** [dylanraga/win11hdr-srgb-to-gamma2.2-icm#25]
Hello and thank you for those profiles.
I've been using this tool for auto HDR games with a great success, however i wonder why do you calibrate specifically with 800 nits for HGIG? The correct value in Windows for 800 nits is 780. With 800 it goes higher than that which is verified with WCG image viewer.
Also any reason why dont you use SDR\HDR slider maxed out and stop at 80%?
Also i've been using unspecified profile, edited with CRU to have peak luminance at 783 for the reasons mentioned above.. as of now this profile stuck at 240 nits with no way to correct :( Probably some windows update messed it up.
In theory is it possible to create a profile for 780 nits peak luminance and maxed out SDR\HDR slider?

**Comment by WilliamLeGod** [comment]
would love a 780 icc too

**Comment by bwellington1** [comment]
I dont even have excel to configure the values myself lol

**Comment by dylanraga** [comment]
There should be almost no discernible difference in the EETF tonemapping between 780 nits and 800 nits. In any case, the value the Windows HDR calibration clips its white pattern isn't the one source of truth for what your MaxTML should be set to. Patterns with different APLs will yield different peak brightness measurements, and the Windows HDR Calibration plays it safe by using a window size of ~10%. Some games uses its own pattern, knowing its own expected content APL, and will give you a result that's better suited to that game, suggesting higher or lower TML values.

On my LG 42C2, I don't use HGIG since it introduces a slight bump to the ST2084 EOTF, raising my 100-nit SDR calibration up to 110 nits. I use DTM Off with Mastering Peak set to 700 so that it doesn't tone map toward 4000 nits, rather to its own correct peak brightness (700 nits), ie minimal tone mapping. On the 42C2, with or without HGIG, the panel has some tone mapping baked in that rolls its 700 nits peak out to 800 nits. On my setup, I can just barely make out the 780 nits frame in the Windows HDR calibration app, and it disappears at 800. Not sure if it was updated recently, but I also double checked the app's patterns and the value 800 in the app does correlate with the PQ value for 800 nits, 780 for 780, 700 for 700. Either way, the _intended_ TML value should be 800 nits if you're using a C2; if it's a bug with the reporting of the HDR calibration app, then the value it reports shouldn't be used (though in my case, it's fine).

As for not providing a profile for 480 nits, I only provided a few profiles spaced about 100 nits apart. 100% on the slider would be 480 nits, and since the perception of luminance is logarithmic, it shouldn't be too different from the transformation provided by the 400 nits profile. If you really want the most granular values, please follow [my tutorial ](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/2#issuecomment-1622575646), viable with Google Sheets, or use the [AutoHotkey script](https://github.com/dylanraga/win11hdr-srgb-to-gamma2.2-icm/issues/7) someone made.

**Comment by dylanraga** [comment]
Had some extra time, so I took my camera and made a little animation showing the difference between MaxTML @ 600 nits, 700 nits, 780 nits, 800 nits, and 1000 nits on my LG 42C2:

https://imgur.com/a/QgVupPS

Can see a very slight difference between 780 and 800 nits, perhaps enough to warrant a tinker, so I retract the first sentence of my previous post.

Here's yours profiles, and probably the last I will be manually making:

Peak 780 nits, SDR 80 nits
https://drive.google.com/file/d/1xVHU9ZBzQ7FdBu3jt5v-J0ThVsj3beIN/view?usp=sharing

Peak 780 nits, SDR 480 nits
https://drive.google.com/file/d/1xVyqkUCDQrV_g11EVr8bp8w7234Ibi-z/view?usp=sharing

**Comment by geahad** [comment]
> Had some extra time, so I took my camera and made a little animation showing the difference between MaxTML @ 600 nits, 700 nits, 780 nits, 800 nits, and 1000 nits on my LG 42C2:
> 
> https://imgur.com/a/JNiwRkn
> 
> Can see a very slight difference between 780 and 800 nits, perhaps enough to warrant a tinker, so I retract the first sentence of my previous post.
> 
> Here's yours profiles, and probably the last I will be manually making:
> 
> Peak 780 nits, SDR 80 nits https://drive.google.com/file/d/1xVHU9ZBzQ7FdBu3jt5v-J0ThVsj3beIN/view?usp=sharing
> 
> Peak 780 nits, SDR 480 nits https://drive.google.com/file/d/1xVyqkUCDQrV_g11EVr8bp8w7234Ibi-z/view?usp=sharing

For this, I'd like to ffer a whole-hearted thank you! <3

If I understood your previous post right, your recommendation is to disable hgig and set the mastering peak to 700? Is this done through the service menu (can't find that setting in the TV's regular settings, and, out of fear of messing up, have not dared to enter service menu).

**Comment by dylanraga** [comment]
You can set the Mastering Peak by inputting "1113111" on the remote while highlighting the Picture Select Mode, which opens the HDMI Signalling Override menu. There's also an option at the bottom to reset the settings / set everything back to 'Auto'.
